### ISSUE TITLE
Default ImageName is null instead of "sysdig_secure_images"

### ISSUE THREAD

**Issue by S0obi** [jenkinsci/sysdig-secure-plugin#110]
### Describe your use-case which is not covered by existing documentation.

The README is stating that ImageName default is "sysdig_secure_images" when it's actually null. 

Doc : https://github.com/jenkinsci/sysdig-secure-plugin/blob/main/README.md?plain=1#L122

The value "sysdig_secure_images" is defined as a constant in the code : https://github.com/jenkinsci/sysdig-secure-plugin/blob/main/src/main/java/com/sysdig/jenkins/plugins/sysdig/infrastructure/jenkins/vm/entrypoint/ImageScanningStep.java#L207 however there is no reference to it.

I think README needs to be changed and clearly state that there is no default value (or null) and the parameter is now mandatory.

**Comment by biru-codeastromer** [comment]
@tembleking hello sir, can i start working on this issue?

**Comment by tembleking** [comment]
Sure @biru-codeastromer :) Thank you!

**Comment by tembleking** [comment]
The parameter is not referenced anymore because that file is not used since the deprecation of the legacy scanner. It has to be removed from code and from the readme.

**Comment by biru-codeastromer** [comment]
okay sir sure @tembleking

**Comment by biru-codeastromer** [comment]
@tembleking hello sir i have updated the issue and solved it and also generated a pr for that..hope you  check it and confirm if the issue is solved..thanks!
